apiVersion: v1
kind: Secret
metadata:
    name: konnect-client-tls
    namespace: kong
data:
    tls.crt: $(cat .certs/tls.crt | base64 | tr -d '\n')
    tls.key: $(cat .certs/tls.key | base64 | tr -d '\n')
type: kubernetes.io/tls
